---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: rails_app_server
    run_list:
      - recipe[stembolt_opsworks::ruby]
    attributes:
